version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '5000:5000'
            - '3000:3000'
        volumes:
            - /app/node_modules
            - /app/client/node_modules
            - .:/app
