version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:5000"
        volumes:
            - /app/node_modules
            - .:/app
